name: GitHub Actions Demo
run-name: ${{ github.actor }} audit stuff
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: does some npm Audit
        run: (cd insecure && npm audit)
    
  Do-Some-Linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Doing some linting?
        run: (cd mashup && npm install eslint-plugin-react@latest --save-dev && npx eslint .eslintrc.js)
